version: 1.0.0.{build}
clone_depth: 5
init:
- git config --global user.email "chocolatey@realdimensions.net"
- git config --global user.name "Chocolatey yo"
nuget:
  disable_publish_on_pr: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: GWDFHkyZwDvbtYzPCHt29njjcm1blAwuTcbT0IEyJZoRSC/soUAa8dwXIlA6l/Fj
build_script:
- build.bat -v
test:
  categories:
    except:
    - ignore
    - Ignore
    - NotWorking
    - notworking
artifacts:
- path: build_output\build_artifacts\compile\msbuild-net-4.0-results.xml
  name: Compile.xml
- path: build_output\build_artifacts\nunit\index.html
  name: NUnitResults.html
- path: build_output\build_artifacts\opencover\Html\index.htm
  name: OpenCoverResults.htm
- path: build_output\_BuildInfo.xml
  name: BuildInfo.xml
- path: build_output\build.log
  name: DetailedBuildLog.log
- path: code_drop\build_artifacts\ilmerge\ilmerge.log
  name: ILMerge.log
- path: code_drop\build_artifacts\ilmerge\ilmergedll.log
  name: ILMergeDLL.log
- path: code_drop\nuget\*.nupkg
notifications:
- provider: Email
  to:
  - chocolatey-build-status@googlegroups.com
  subject: AppVeyor - choco Build Notification
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
- provider: Webhook
  url: https://webhooks.gitter.im/e/ef0d02785675d16d0cad
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
